// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcybtaozfuwoylpjlvzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjeWJ0YW96ZnV3b3lscGpsdnpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwMDE2ODcsImV4cCI6MjA1NTU3NzY4N30.psVYSC0NKIGZR5PybjqOWe8WawM5nLR_kcEgFr4PPHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);